spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    master:
      hikari:
        username: kty
        password: qwer1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.72.30/shop
    slave:
      hikari:
        username: kty
        password: qwer1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.72.30/shop

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

project:
  upload:
    path: C:\lonua\brand
    product-path: C:\lonua\product\images
    product-introduction-path: C:\lonua\product\introductionimages

jwt:
  secret-key: abcdefghijklmnopqrstuvwxyz0123456789
  token:
    expired-time-ms: 3000000